kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: compass-report-script
  annotations:
    description: "Template to generate a report script which when triggered by the cronjob writes some status data to a google sheet"
    tags: "COMPASS, Python, Google Sheets"
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: google-services-credentials
      labels:
        app: compass-backend
    type: Opaque
    data:
      google-services-credentials.json: ${GOOGLE_SERVICES_JSON}
  - kind: Secret
    apiVersion: v1
    metadata:
      name: spreadsheet-id
      labels:
        app: compass-backend
        app.kubernetes.io/component: mobile-backend
        app.kubernetes.io/name: ${APP_NAME}
        app.kubernetes.io/instance: ${APP_NAME}-${INSTANCE_IDENTIFIER}
        app.kubernetes.io/part-of: ${HIGH_LVL_APP_NAME}
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: report-script
      annotations:
        app.openshift.io/vcs-ref: ${GIT_BRANCH}
        app.openshift.io/vcs-uri: ${APP_GIT_URL}
        app.kubernetes.io/component: mobile-backend
        app.kubernetes.io/name: ${APP_NAME}
        app.kubernetes.io/instance: ${APP_NAME}-${INSTANCE_IDENTIFIER}
        app.kubernetes.io/part-of: ${HIGH_LVL_APP_NAME}
        app.openshift.io/runtime: python
        app.openshift.io/runtime-version: "3.9-ubi8"
      labels:
        app: compass-backend
      spec:
        nodeSelector: null
        output:
          to:
            kind: ImageStreamTag
            name: report-script
        resources: {}
        successfulBuildsHistoryLimit: 5
        failedBuildsHistoryLimit: 5
        strategy:
          type: Docker
          dockerStrategy:
            from:
              kind: ImageStream
              namespace: openshift
              name: "python:3.9-ubi8"
        postCommit: {}
        source:
          type: Git
          git:
            uri: ${APP_GIT_URL}
            ref: ${GIT_BRANCH}
          contextDir: /
          sourceSecret:
            name: mobile-backend-git-access-cert
        triggers:
          - type: ConfigChange
        runPolicy: serial
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      annotations:
        app.openshift.io/vcs-ref: ${GIT_BRANCH}
        app.openshift.io/vcs-uri: ${APP_GIT_URL}
      name: report-script
      labels:
        app: sa-lmu
        app.kubernetes.io/component: report-script
        app.kubernetes.io/name: ${APP_NAME}
        app.kubernetes.io/instance: ${APP_NAME}-${INSTANCE_IDENTIFIER}
        app.kubernetes.io/part-of: ${HIGH_LVL_APP_NAME}
        app.openshift.io/runtime: python
        app.openshift.io/runtime-version: "3.9-ubi8"
    spec: {}
  - kind: CronJob
    apiVersion: batch/v1
    metadata:
      labels:
        app: report-script
        app.kubernetes.io/component: report-script
        app.kubernetes.io/name: report-script
        app.kubernetes.io/instance: ${APP_NAME}-${INSTANCE_IDENTIFIER}
        app.kubernetes.io/part-of: ¢{HIGH_LVL_APP_NAME}
    spec:
      schedule: "0 8 * * 5"
      failedJobsHistoryLimit: 5
      successfulJobsHistoryLimit:
      concurrencyPolicy: "Replace"
      jobTemplate:
        spec:
          template:
            metadata:
              name: report-script
            spec:
              containers:
                - name: report-script
                  image: report-script:prod
                  envFrom:
                    - secretRef:
                      name: database-creds
                    - configMapRef:
                      name: mobile-backend-env
                    - secretRef:
                      name: spreadsheet-id
                  volumeMounts:
                - name: secrets
                  mountPath: /opt/app-root/secrets
                  readOnly: true
                  command: ["python", "report-script.py"]
              volumes:
                - name: secrets
                  secret:
                    secretName: google-services-credentials
              restartPolicy: Never
parameters:
  - name: APP_GIT_URL
    description: The Git URL for the source code
    required: true
  - name: GIT_BRANCH
    description: The Git branch that should be used for new builds
    value: main
  - name: APP_NAME
    description: name of the application
    required: true
  - name: GOOGLE_SERVICES_JSON
    description: google-services-credentials required to access the spreadsheet
    required: true
  - name: SPREADSHEET_ID
    description: ID of the spreadsheet to which the application shall write the data
  - name: HIGH_LVL_APP_NAME
    description: Name of the higher level application that a resource is part of
    value: SAM-LMU
  - name: INSTANCE_IDENTIFIER
    description: Unique identifier for resources
    generate: expression
    from: "[a-zA-Z0-9]{5}"
